### ISSUE TITLE
Stuck on "Decompiler Running....."

### ISSUE THREAD

**Issue by 0xAwayy** [Martyx00/ghinja#9] opened 2021-12-27 01:38 UTC
Ive installed ghinja both through the Binary Ninja plugin manager and manually through the repo. I set the target to analyzeHeadless, yet when I click anywhere in the dock to run the decompiler, it hangs on "Decompiler Running" 

Binary Ninja Version 2.4.2846
Ghidra version 10.0.4 
Macbook Pro M1

Thanks :)

**Comment by Martyx00** [comment] 2021-12-27 16:29
The simplest thing that can happen is that after reinstalling Ghidra you may need to, re-enter the path to the JDK. Whether this is the reason for it being stuck can be checked by running `binaryninja` from terminal. The Ghidra commands should output to that terminal session. It will also show any other errors which may have occurred and prevented the decompilation. If this is not the cause, please share the output of of the Decompiler attempt which is echoed to the terminal.

**Comment by 0xAwayy** [comment] 2021-12-27 18:29
I managed to fix it by renaming Decompile_TEMPLATE.java to Decompile.java the issue is when you're naming the class 
in accordance with the java file. Thank you for the tip on running binja from terminal. Have a nice day : )

**Comment by Martyx00** [comment] 2021-12-27 18:56
If the `Decompile_TEMPLATE.java` file was what caused the problem renaming it to `Decompile.java` will actually break the plugin as the template file contains [placeholders](https://github.com/Martyx00/ghinja/blob/ae52bca3ce2a094a9046d1c7b4020415fd4a09fd/Decompile_TEMPLATE.txt#L60) and is used to create a new copy for each run. In case that with new version of Ghidra this causes issues, I have updated the plugin to use `.txt` extension for the file rather than `.java`. This will ensure that Ghidra will ignore the file.

**Comment by Martyx00** [comment] 2021-12-27 19:00
In brief tests that I have run it seems that the `analyzeHeadless` hangs for some reason. Once it is done (you can tell by the output in the console) close the Ghinja dock and open it again and it should work. I will look into why the Ghidra hangs in coming days/weeks. Thanks for reporting.

**Comment by 0xAwayy** [comment] 2021-12-27 19:03
Yup, analyzeHeadless does seem to hang. Weird, although your fix did help for the time being. Thank you and good luck with your endeavors on updated the plugin 👍

**Comment by Martyx00** [comment] 2021-12-28 13:53
It was just a UI problem. Fixed with a pop-up message that notifies user when Ghidra decompiler is done. After that pop-up selecting a function will make the code appear in the dock.

**Closed by Martyx00** 2021-12-28 13:53 UTC
